# Generated by Django 4.2.7 on 2023-11-27 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_messages_room_alter_room_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="chat.room"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
